:spring_version: current
:toc:
:project_id: gs-spring-boot-docker
:icons: font
:source-highlighter: prettify

This guide walks you through the process of building a https://docker.com[Docker] image for running a Spring Boot application. We start with a basic `Dockerfile` and make a few tweaks. Then we show a couple of options that use build plugins (for Maven and Gradle) instead of `docker`. This is a "`getting started`" guide, so the scope is limited to a few basic needs. If you are building container images for production use, there are many things to consider, and it is not possible to cover them all in a short guide.

== What You Will Build
https://docker.com[Docker] is a Linux container management toolkit with a "`social`" aspect, letting users publish container images and consume those published by others. A Docker image is a recipe for running a containerized process. In this guide, we build one for a simple Spring boot application.

[[initial]]
== Set up a Spring Boot Application

Now you can create a simple application:

====
`src/main/java/hello/Application.java`
[source,java,tabsize=2]
----
include::complete/src/main/java/hello/Application.java[]
----
====

The class is flagged as a `@SpringBootApplication` and as a `@RestController`, meaning that it is ready for use by Spring MVC to handle web requests. `@RequestMapping` maps `/` to the `home()` method, which sends a `Hello World` response. The `main()` method uses Spring Boot's `SpringApplication.run()` method to launch an application.

Now we can run the application without the Docker container (that is, in the host OS):

If you use Gradle, run the following command:

====
[bash,subs="attributes"]
----
./gradlew build && java -jar build/libs/{project_id}-0.1.0.jar
----
====

Then go to http://localhost:8080[localhost:8080] to see your "`Hello Docker World`" message.

== Containerize It

Docker has a simple https://docs.docker.com/reference/builder/["Dockerfile"] file format that it uses to specify the "`layers`" of an image. Create the following Dockerfile in your Spring Boot project:

.Dockerfile
====
[source]
----
FROM openjdk:8-jdk-alpine
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
----
====

If you use Gradle, you can run it with the following command:

====
[source,bash,subs="attributes"]
----
docker build -t gs-spring-boot-docker:0.1.0  --build-arg JAR_FILE=build/libs/gs-spring-boot-docker-0.1.0.jar .
----
====

This command builds an image and tags it as `gs-spring-boot-docker:0.1.0`.

This Dockerfile is very simple, but it is all you need to run a Spring Boot app with no frills: just Java and a JAR file. The build creates a spring user and a spring group to run the application. It is then copied (by the `COPY` command) the project JAR file into the container as `app.jar`, which is run in the `ENTRYPOINT`. The array form of the Dockerfile `ENTRYPOINT` is used so that there is no shell wrapping the Java process. The https://spring.io/guides/topicals/spring-boot-docker[Topical Guide on Docker] goes into this topic in more detail.


Running applications with user privileges helps to mitigate some risks (see, for example, https://security.stackexchange.com/questions/106860/can-a-root-user-inside-a-docker-lxc-break-the-security-of-the-whole-system[a thread on StackExchange]).
So, an important improvement to the `Dockerfile` is to run the application as a non-root user:

.Dockerfile
====
[source]
----
FROM openjdk:8-jdk-alpine
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
----
====

You can see the username in the application startup logs when you build and run the application:

====
[source,bash]
----
docker build -t gs-spring-boot-docker:0.1.0 .
docker run -p 8080:8080 gs-spring-boot-docker:0.1.0
----
====

Note the `started by` in the first `INFO` log entry:

====
[source,bash]
----
 :: Spring Boot ::        (v2.2.1.RELEASE)

2020-04-23 07:29:41.729  INFO 1 --- [           main] hello.Application                        : Starting Application on b94c86e91cf9 with PID 1 (/app started by spring in /)
...
----
====


=== Using Spring Profiles

Running your freshly minted Docker image with Spring profiles is as easy as passing an environment variable to the Docker run command (for the `prod` profile):

====
[source,bash]
----
docker run -e "SPRING_PROFILES_ACTIVE=prod" -p 8080:8080 -t gs-spring-boot-docker:0.1.0
----
====

You can do the same for the `dev` profile:

====
----
docker run -e "SPRING_PROFILES_ACTIVE=dev" -p 8080:8080 -t gs-spring-boot-docker:0.1.0
----
====

== Summary

Congratulations! You have created a Docker container for a Spring Boot application! By default, Spring Boot applications run on port 8080 inside the container, and we mapped that to the same port on the host by using `-p` on the command line.
